---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity<-read.csv("activity.csv")


## What is mean total number of steps taken per day?
steps_sum<-aggregate(steps~date,data=activity,FUN="sum")
hist(steps_sum$steps)
summary(steps_sum$steps)

## What is the average daily activity pattern?
steps_by_interval<-aggregate(steps~interval,data=activity,FUN="mean")
plot(steps_by_interval$interval,steps_by_interval$steps,pch=c(0),type="l")
steps_by_interval$interval[which.max(steps_by_interval$steps)]

## Imputing missing values
str(activity[is.na(activity$steps),] )
impute.mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
activity_filled <- ddply(activity, ~ interval, transform, steps = impute.mean(steps))
steps_by_interval_filled<-aggregate(steps~interval,data=activity_filled,FUN="mean")
plot(steps_by_interval_filled$interval,steps_by_interval_filled$steps,pch=c(0),type="l")


steps_by_interval_filled<-aggregate(steps~interval,data=activity_filled,FUN="median")
plot(steps_by_interval_filled$interval,steps_by_interval_filled$steps,pch=c(0),type="l")
steps_by_interval<-aggregate(steps~interval,data=activity,FUN="median")
plot(steps_by_interval$interval,steps_by_interval$steps,pch=c(0),type="l")


## Are there differences in activity patterns between weekdays and weekends?
activity_filled$daytype=ifelse(weekdays(as.Date(activity_filled$date))=="星期六"|weekdays(as.Date(activity_filled$date))=="星期日","weekends", "weekdays")
activity_filled$daytype=as.factor(activity_filled$daytype)
activity_filled_weekday<-activity_filled[activity_filled$daytype=="weekdays",]
activity_filled_weekend<-activity_filled[activity_filled$daytype=="weekends",]
par(mfrow=c(2,1))
activity_filled_weekend_aggr=aggregate(steps~interval,data=activity_filled_weekend,FUN="mean")
plot(activity_filled_weekend_aggr$interval,activity_filled_weekend_aggr$steps,pch=c(0),type="l")

activity_filled_weekday=aggregate(steps~interval,data=activity_filled_weekday,FUN="mean")
plot(activity_filled_weekday$interval,activity_filled_weekday$steps,pch=c(0),type="l")
